# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id:
      conn_type:
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: POSTGRES_HOST
      variable_value: capstone-db.clkqgo82o8se.us-east-2.rds.amazonaws.com
    - variable_name: POSTGRES_DB
      variable_value: postgres
    - variable_name: POSTGRES_USER
      variable_value: postgres
    - variable_name: POSTGRES_PASSWORD
      variable_value: iD1*PIMRPXvFejCT
