"""Supporting extract and upload s3

Revision ID: 61b3c704bb42
Revises: d684085d11d1
Create Date: 2025-02-20 02:34:00.888758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b3c704bb42'
down_revision: Union[str, None] = 'd684085d11d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_news', sa.Column('keyword', sa.String(length=255), nullable=False))
    op.drop_column('dim_news', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_news', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('dim_news', 'keyword')
    # ### end Alembic commands ###
