"""news + stocks basic schema_2

Revision ID: d684085d11d1
Revises: 
Create Date: 2025-02-16 00:07:30.643170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd684085d11d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_news',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', postgresql.ENUM('NEWS_API', 'YAHOO_NEWS', name='source_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('press_veichle', sa.String(length=255), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('s3_url', sa.String(length=255), nullable=False),
    sa.Column('dt_published_at', sa.DateTime(), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('dim_stocks',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', postgresql.ENUM('US', 'BR', 'CRYPTO', name='market_enum'), nullable=False),
    sa.Column('company_info', sa.Text(), nullable=True),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=False),
    sa.Column('dt_last_analyzed', sa.DateTime(), nullable=True),
    sa.Column('dt_last_scraped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('dim_stock_prices',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_stock_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('no_trades', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fk_stock_id'], ['dim_stocks.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_stock_prices')
    op.drop_table('dim_stocks')
    op.drop_table('dim_news')
    # ### end Alembic commands ###
