stocks:
  us_stocks:
    market: NASDAQ
    - symbol: GOOGL
      name: Alphabet Inc.
      keywords:
        - Privacy
        - Regulation
        - Antitrust

    - symbol: NVDA
      name: NVIDIA Corporation
      keywords:
        - Supply Chain
        - Geopolitics
        - Data Centers

    - symbol: MSFT
      name: Microsoft Corporation
      keywords:
        - Cybersecurity
        - Layoffs

    - symbol: AMZN
      name: Amazon.com, Inc.
      keywords:
        - Inflation
        - Interest Rates
        - Recession

    - symbol: META
      name: Meta Platforms, Inc. Class A
      keywords:
        - Privacy
        - Content Moderation

  crypto_stocks:
    market: CRYPTO
    - symbol: BTC
      name: Bitcoin

    - symbol: ETH
      name: Ethereum

    - symbol: SOL
      name: Solana

    - symbol: XRP
      name: Ripple

    - symbol: ADA
      name: Cardano
